# Crowdin Configuration File
# This maps your local file structure to the Crowdin project
# Norwegian translations required mapping because Crowdin uses 'no' (generic) for Google Translate, but Home Assistant requires 'nb' (Bokmål).

preserve_hierarchy: true

files:
  # 1. Main Integration Translations
  # Maps: /translations/en.json -> /translations/fr.json
  - source: /custom_components/kidschores/translations/en.json
    translation: /custom_components/kidschores/translations/%two_letters_code%.json
    languages_mapping:
      two_letters_code:
        "no": nb

  # 2. Dashboard Translations (custom translations directory)
  # Maps: /translations_custom/en_dashboard.json -> /translations_custom/fr_dashboard.json
  - source: /custom_components/kidschores/translations_custom/en_dashboard.json
    translation: /custom_components/kidschores/translations_custom/%two_letters_code%_dashboard.json
    languages_mapping:
      two_letters_code:
        "no": nb

  # 3. Notification Translations (custom translations directory)
  # Maps: /translations_custom/en_notifications.json -> /translations_custom/fr_notifications.json
  - source: /custom_components/kidschores/translations_custom/en_notifications.json
    translation: /custom_components/kidschores/translations_custom/%two_letters_code%_notifications.json
    languages_mapping:
      two_letters_code:
        "no": nb
